version: '3.9'
services:
  beatport-analysis-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    ports:
      - '5000:5000'
  # beatport-analysis-db:
  #   image: "mysql:latest"
