version: '3.9'
services:
  beatport-analysis-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - MYSQL_USER=root
      - MYSQL_HOST=beatport-analysis-db
      - MYSQL_DATABASE=luke_dev
      - MYSQL_PASSWORD=belly123
      - MYSQL_PORT=3306
    ports:
      - '5000:5000'

  beatport-analysis-db:
    image: 'mysql:latest'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=belly123
      - MYSQL_DATABASE=luke_dev
